allowBuilds:
  '@google/genai': true
  '@hugeicons/svelte': true
  '@prisma/engines': true
  agent-browser: true
  bufferutil: true
  edgedriver: true
  esbuild: true
  geckodriver: true
  msgpackr-extract: true
  msw: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
